"""
Re-apply the current feedback rules (Phase 1 skip, Phase 5 auto-match)
to the EXISTING pending-review queue.

When a new phase ships, it only changes how *future* emails are
triaged. Drafts already sitting in the inbox were generated by an
older matcher — internal-domain senders not yet auto-skipped, real
clients matched to the wrong project, etc. This script walks the
pending queue once and brings every row up to current rules:

  * Phase 1 hits  → mark reviewed (auto_skipped, drop from queue)
  * Phase 5 hits  → update project_id to the learned-match winner
                    (don't archive — the draft text still wants
                    Toby's eye, just route it right)

Idempotent: re-running is harmless.

Usage:
    docker exec -w /app -e PYTHONPATH=/app deploy-deek-api-1 \\
        python -m scripts.email_triage.reevaluate_pending [--commit]
"""
from __future__ import annotations

import argparse
import logging
import os
import sys

import psycopg2

logging.basicConfig(level=logging.INFO, format='%(message)s')
log = logging.getLogger('reevaluate_pending')


def reevaluate(commit: bool) -> dict:
    from core.triage.feedback_rules import (
        should_skip_drafting,
        format_skip_note,
    )
    from core.triage.sender_associations import auto_match_for

    db = os.getenv('DATABASE_URL')
    if not db:
        raise SystemExit('DATABASE_URL not set')
    conn = psycopg2.connect(db)
    stats = {
        'scanned': 0,
        'auto_skipped': 0,
        'auto_matched': 0,
        'rerouted_to_different_project': 0,
        'unchanged': 0,
    }

    with conn.cursor() as cur:
        # Pull every pending row with a draft. This is what Toby
        # would actually see in /dashboard/inbox.
        cur.execute(
            """
            SELECT id, email_sender, email_subject, project_id, draft_reply
              FROM cairn_intel.email_triage
             WHERE reviewed_at IS NULL
               AND draft_reply IS NOT NULL
             ORDER BY processed_at DESC
            """
        )
        rows = cur.fetchall()

    stats['scanned'] = len(rows)
    log.info('scanning %d pending rows', len(rows))

    skip_updates = []
    match_updates = []

    for triage_id, sender, subject, project_id, _draft in rows:
        # Phase 1 — would Deek auto-skip this sender today?
        skip = should_skip_drafting(sender or '')
        if skip is not None:
            skip_updates.append((triage_id, sender, format_skip_note(skip)))
            stats['auto_skipped'] += 1
            continue

        # Phase 5 — has Deek learned a clear winner for this sender?
        # Only act if it's different from the current project_id —
        # we don't churn rows that are already routed correctly.
        am = auto_match_for(sender or '')
        if am and am['project_id'] != (project_id or ''):
            match_updates.append((triage_id, sender, project_id, am))
            stats['auto_matched'] += 1
            if project_id:
                stats['rerouted_to_different_project'] += 1
            continue

        stats['unchanged'] += 1

    log.info(
        'plan: auto-skip=%d  re-route=%d  (of which different-project=%d)  unchanged=%d',
        stats['auto_skipped'],
        stats['auto_matched'],
        stats['rerouted_to_different_project'],
        stats['unchanged'],
    )

    if not commit:
        log.info('--dry-run (no --commit). Sample of planned changes:')
        for t_id, sender, note in skip_updates[:5]:
            log.info('  SKIP  #%d %s → %s', t_id, sender[:40], note)
        for t_id, sender, old_pid, am in match_updates[:5]:
            log.info(
                '  MATCH #%d %s  %s → %s (score=%.2f)',
                t_id, sender[:40], old_pid or '(none)',
                am['project_id'][:12], am['score'],
            )
        return stats

    # Apply skip updates — these drop from the queue immediately.
    with conn.cursor() as cur:
        for t_id, sender, note in skip_updates:
            cur.execute(
                """
                UPDATE cairn_intel.email_triage
                   SET reviewed_at = NOW(),
                       review_action = 'auto_skipped',
                       review_notes = COALESCE(NULLIF(review_notes,''), '')
                                       || E'\nretroactive ' || %s
                 WHERE id = %s AND reviewed_at IS NULL
                """,
                (note, t_id),
            )
        # Apply project_id updates — the row stays in the queue with
        # the correct project so the inbox UI re-groups it.
        for t_id, sender, old_pid, am in match_updates:
            note = (
                f'retroactive auto-match by learned association: '
                f'{old_pid or "(none)"} → {am["project_id"]} '
                f'(score={am["score"]:.2f}, '
                f'actions={am["evidence"]["total_actions"]})'
            )
            cur.execute(
                """
                UPDATE cairn_intel.email_triage
                   SET project_id = %s,
                       project_match_score = %s,
                       review_notes = COALESCE(NULLIF(review_notes,''), '')
                                       || E'\n' || %s
                 WHERE id = %s AND reviewed_at IS NULL
                """,
                (am['project_id'], float(am['score']), note, t_id),
            )
        conn.commit()

    log.info('committed.')
    return stats


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser()
    p.add_argument('--commit', action='store_true',
                   help='actually write; otherwise dry-run')
    args = p.parse_args(argv)
    result = reevaluate(commit=args.commit)
    print(result)
    return 0


if __name__ == '__main__':
    sys.exit(main())
